# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run the parafit algorithm
#'
#' Run the parafit algorithm to obtain the global test statistics and obtain a test
#' of significance using permutation. Optionally, obtain tests of individual associations.
#'
#' @param assoA association matrix
#' @param paraB parasite principal coordinates
#' @param hostC transposed host principal coordinates
#' @param permutations number of permutations
#' @param seed random seed value
#'
#' @return vector of trace statistics
pf_parafit_cpp <- function(assoA, paraB, hostC, permutations, seed) {
    .Call(`_parafit_pf_parafit_cpp`, assoA, paraB, hostC, permutations, seed)
}

#' Obtain Principal Coordinate from a distance matrix
#'
#' Obtain principal coordinates from a distance matrix (triangle or square)
#'
#' @param x a distance matrix
#'
#' @return matrix of principal coordinates
pf_pcoa_cpp <- function(x) {
    .Call(`_parafit_pf_pcoa_cpp`, x)
}

